### ISSUE TITLE
Owner fields correction

### ISSUE THREAD

**Issue by merchanf** [Rawr-IngeSoft/RawrProject#26]
The owner field in the database table, should have an email, a birth
 date and a gender and shouldn't have an address field, we don't care about where the user lives, but maybe a city and a country field would be useful for us.

![db issue](https://cloud.githubusercontent.com/assets/9278608/7503762/a5cb6d46-f40a-11e4-8e20-72f3f68b23cf.png)

**Comment by a-santamaria** [comment]
country and city are referenced by idLocation. The address field is not necessary at all?

**Comment by merchanf** [comment]
I don't think so, we should we know exactly the place where the users live? If that informations were filtered, would be terrible for them and for us. And respect to the location table, you're right I'm sorry i didn't noticed that table.

**Comment by a-santamaria** [comment]
ok thanks... done!
